create table if not exists company_watchlist (
  company text primary key,
  sector text not null,
  careers_url text,
  priority smallint not null default 2 check (priority between 1 and 3),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table company_watchlist enable row level security;

insert into company_watchlist(company, sector, careers_url, priority, enabled) values
-- Tier 1: explicitly requested / strongest target universe
('Cohere','AI & software','https://cohere.com/careers',1,true),
('Shopify','Technology','https://www.shopify.com/careers',1,true),
('Google','Technology','https://www.google.com/about/careers/applications/jobs/results/',1,true),
('Microsoft','Technology','https://jobs.careers.microsoft.com/global/en/search',1,true),
('Amazon','Technology','https://www.amazon.jobs/en/search',1,true),
('IBM','Technology & consulting','https://www.ibm.com/careers/search',1,true),
('RBC','Banking','https://jobs.rbc.com/',1,true),
('TD','Banking','https://jobs.td.com/en-CA/',1,true),
('BMO','Banking','https://jobs.bmo.com/ca/en',1,true),
('CIBC','Banking','https://www.cibc.com/en/about-cibc/careers.html',1,true),
('Scotiabank','Banking','https://jobs.scotiabank.com/',1,true),
('Manulife','Insurance & financial services','https://careers.manulife.com/',1,true),
('Sun Life','Insurance & financial services','https://www.sunlife.ca/en/careers/',1,true),
('Bell','Telecommunications','https://jobs.bce.ca/bell/',1,true),
('Rogers','Telecommunications','https://jobs.rogers.com/',1,true),
('TELUS','Telecommunications','https://www.telus.com/en/about/careers',1,true),
('OpenText','Enterprise software','https://careers.opentext.com/',1,true),
('BlackBerry','Enterprise software','https://www.blackberry.com/us/en/company/careers',1,true),
('PointClickCare','Health technology','https://careers.pointclickcare.com/',1,true),
('Kinaxis','Enterprise software','https://www.kinaxis.com/en/careers',1,true),
('Geotab','Technology','https://careers.geotab.com/',1,true),
('Clio','Technology','https://www.clio.com/about/careers/',1,true),
('StackAdapt','Ad technology','https://www.stackadapt.com/careers',1,true),
('Wealthsimple','Fintech','https://www.wealthsimple.com/en-ca/careers',1,true),
('Faire','Technology','https://www.faire.com/careers',1,true),
('Hootsuite','Technology','https://careers.hootsuite.com/',1,true),
('1Password','Cybersecurity','https://1password.com/jobs',1,true),
('Ada','AI & software','https://www.ada.cx/careers',1,true),
('Waabi','AI & autonomous systems','https://waabi.ai/careers',1,true),
('Coveo','AI & enterprise software','https://www.coveo.com/en/company/careers',1,true),
('Thomson Reuters','Information & software','https://careers.thomsonreuters.com/',1,true),
('Deloitte','Consulting','https://www.deloitte.com/ca/en/careers.html',1,true),
('PwC','Consulting','https://www.pwc.com/ca/en/careers.html',1,true),
('EY','Consulting','https://www.ey.com/en_ca/careers',1,true),
('KPMG','Consulting','https://kpmg.com/ca/en/home/careers.html',1,true),
('Accenture','Consulting & technology','https://www.accenture.com/ca-en/careers/jobsearch',1,true),
('Oracle','Enterprise software','https://www.oracle.com/careers/',1,true),
('SAP','Enterprise software','https://jobs.sap.com/',1,true),

-- AI, cloud, developer platforms and major global technology employers
('OpenAI','AI & software','https://openai.com/careers/',2,true),
('Anthropic','AI & software','https://www.anthropic.com/careers',2,true),
('NVIDIA','Semiconductors & AI','https://www.nvidia.com/en-us/about-nvidia/careers/',2,true),
('AMD','Semiconductors','https://careers.amd.com/',2,true),
('Intel','Semiconductors','https://jobs.intel.com/',2,true),
('Apple','Technology','https://jobs.apple.com/',2,true),
('Meta','Technology','https://www.metacareers.com/jobs/',2,true),
('Salesforce','Enterprise software','https://careers.salesforce.com/',2,true),
('ServiceNow','Enterprise software','https://careers.servicenow.com/',2,true),
('Snowflake','Data cloud','https://careers.snowflake.com/',2,true),
('Databricks','Data & AI','https://www.databricks.com/company/careers/open-positions',2,true),
('MongoDB','Data & software','https://www.mongodb.com/company/careers',2,true),
('Elastic','Data & software','https://www.elastic.co/careers',2,true),
('Cloudflare','Cloud & cybersecurity','https://www.cloudflare.com/careers/jobs/',2,true),
('Cisco','Networking & cloud','https://jobs.cisco.com/',2,true),
('Okta','Cybersecurity','https://www.okta.com/company/careers/',2,true),
('Palo Alto Networks','Cybersecurity','https://jobs.paloaltonetworks.com/',2,true),
('CrowdStrike','Cybersecurity','https://www.crowdstrike.com/en-us/careers/',2,true),
('GitHub','Developer tools','https://www.github.careers/careers-home',2,true),
('GitLab','Developer tools','https://about.gitlab.com/jobs/',2,true),
('Atlassian','Developer tools','https://www.atlassian.com/company/careers',2,true),
('Stripe','Fintech & software','https://stripe.com/jobs/search',2,true),
('Block','Fintech & software','https://block.xyz/careers/jobs',2,true),
('PayPal','Fintech','https://paypal.eightfold.ai/careers',2,true),
('Uber','Technology','https://www.uber.com/us/en/careers/list/',2,true),
('Airbnb','Technology','https://careers.airbnb.com/positions/',2,true),
('DoorDash','Technology','https://careersatdoordash.com/jobs/',2,true),
('Instacart','Technology','https://instacart.careers/current-openings/',2,true),
('Reddit','Technology','https://www.redditinc.com/careers',2,true),
('Adobe','Software','https://careers.adobe.com/us/en',2,true),
('Autodesk','Software','https://autodesk.wd1.myworkdayjobs.com/Ext',2,true),
('Electronic Arts','Gaming & software','https://www.ea.com/careers',2,true),
('Unity','Gaming & software','https://careers.unity.com/',2,true),

-- Canadian technology, fintech and growth companies
('Lightspeed','Fintech & software','https://www.lightspeedhq.com/careers/',2,true),
('Nuvei','Fintech','https://www.nuvei.com/careers/',2,true),
('Questrade','Fintech','https://www.questrade.com/about-us/careers',2,true),
('Neo Financial','Fintech','https://www.neofinancial.com/careers',2,true),
('KOHO','Fintech','https://www.koho.ca/careers/',2,true),
('Float','Fintech','https://floatfinancial.com/careers',2,true),
('Equitable Bank','Banking & fintech','https://eqb.influitive.com/careers',2,true),
('National Bank of Canada','Banking','https://jobs.nbc.ca/',2,true),
('Bank of Canada','Financial services','https://www.bankofcanada.ca/careers/',2,true),
('CPP Investments','Investment management','https://www.cppinvestments.com/careers/',2,true),
('OMERS','Investment management','https://www.omers.com/careers',2,true),
('Ontario Teachers'' Pension Plan','Investment management','https://www.otpp.com/en-ca/about-us/careers/',2,true),
('Vena Solutions','Enterprise software','https://www.venasolutions.com/careers',2,true),
('Loopio','Enterprise software','https://loopio.com/careers/',2,true),
('BenchSci','AI & health technology','https://www.benchsci.com/careers',2,true),
('League','Health technology','https://league.com/careers/',2,true),
('FreshBooks','Fintech & software','https://www.freshbooks.com/careers',2,true),
('ApplyBoard','Education technology','https://www.applyboard.com/careers',2,true),
('D2L','Education technology','https://www.d2l.com/careers/',2,true),
('Docebo','Education technology','https://www.docebo.com/company/careers/',2,true),
('Jane App','Health technology','https://jane.app/careers',2,true),
('TouchBistro','Hospitality technology','https://www.touchbistro.com/careers/',2,true),
('Hopper','Travel technology','https://www.hopper.com/careers',2,true),
('Plusgrade','Travel technology','https://www.plusgrade.com/careers/',2,true),
('Thinkific','Education technology','https://www.thinkific.com/careers/',2,true),
('Arctic Wolf','Cybersecurity','https://arcticwolf.com/company/careers/',2,true),
('Magnet Forensics','Cybersecurity','https://www.magnetforensics.com/careers/',2,true),
('Axonify','Education technology','https://axonify.com/careers/',2,true),
('Wattpad','Technology & media','https://company.wattpad.com/jobs',2,true),
('SSENSE','E-commerce & technology','https://www.ssense.com/en-ca/careers',2,true),

-- Consulting, systems integration, ERP and enterprise services
('CGI','IT services & consulting','https://www.cgi.com/en/careers',2,true),
('Capgemini','IT services & consulting','https://www.capgemini.com/ca-en/careers/',2,true),
('Cognizant','IT services & consulting','https://careers.cognizant.com/global-en/',2,true),
('Infosys','IT services & consulting','https://www.infosys.com/careers/',2,true),
('TCS','IT services & consulting','https://www.tcs.com/careers',2,true),
('Wipro','IT services & consulting','https://careers.wipro.com/',2,true),
('NTT DATA','IT services & consulting','https://careers.nttdata.com/',2,true),
('Avanade','Microsoft consulting','https://www.avanade.com/en/career',2,true),
('Slalom','Consulting','https://www.slalom.com/careers',2,true),
('MNP','Consulting','https://www.mnp.ca/en/careers',2,true),
('Workday','Enterprise software','https://workday.wd5.myworkdayjobs.com/Workday',2,true),
('Salesforce Canada','Enterprise software','https://careers.salesforce.com/',2,true),

-- Insurance and financial-services employers
('Intact','Insurance','https://careers.intactfc.com/',2,true),
('Canada Life','Insurance','https://www.canadalife.com/about-us/careers.html',2,true),
('Desjardins','Financial services','https://www.desjardins.com/ca/careers/',2,true),
('Co-operators','Insurance','https://careers.cooperators.ca/',2,true),
('Definity','Insurance','https://www.definityfinancial.com/careers/',2,true),
('Munich Re Canada','Insurance','https://www.munichre.com/ca-non-life/en/company/careers.html',3,true),

-- Telecommunications, infrastructure and industrial technology
('Ericsson','Telecommunications','https://www.ericsson.com/en/careers',2,true),
('Nokia','Telecommunications','https://www.nokia.com/about-us/careers/',2,true),
('SaskTel','Telecommunications','https://www.sasktel.com/about-us/careers',3,true),
('Videotron','Telecommunications','https://corpo.videotron.com/en/careers',3,true),
('Siemens','Industrial technology','https://www.siemens.com/global/en/company/jobs.html',2,true),
('Schneider Electric','Industrial technology','https://www.se.com/ww/en/about-us/careers/',2,true),
('Honeywell','Industrial technology','https://careers.honeywell.com/',2,true),
('ABB','Industrial technology','https://careers.abb/global/en',2,true),
('Bosch','Industrial technology','https://www.bosch.ca/careers/',2,true),
('3M','Industrial technology','https://3m.wd1.myworkdayjobs.com/Search',3,true),

-- Automotive and Windsor/Ontario-relevant employers
('Stellantis','Automotive','https://careers.stellantis.com/',1,true),
('Ford','Automotive','https://efds.fa.em5.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1',2,true),
('General Motors','Automotive','https://search-careers.gm.com/en/jobs/',2,true),
('Magna International','Automotive','https://jobs.magna.com/',2,true),
('Linamar','Manufacturing','https://www.linamar.com/careers/',2,true),
('Toyota Canada','Automotive','https://www.toyota.ca/toyota/en/careers',3,true),
('Honda Canada','Automotive','https://www.honda.ca/careers',3,true),

-- Public-sector / research-heavy employers useful for data, IT and AI roles
('Government of Canada','Public sector','https://www.canada.ca/en/services/jobs/opportunities/government.html',3,true),
('Ontario Public Service','Public sector','https://www.gojobs.gov.on.ca/',3,true),
('City of Toronto','Public sector','https://jobs.toronto.ca/jobsatcity/',3,true),
('University of Windsor','Higher education','https://www.uwindsor.ca/humanresources/317/employment-opportunities',3,true),
('University of Toronto','Higher education','https://jobs.utoronto.ca/',3,true),
('University of Waterloo','Higher education','https://careers-uwaterloo.icims.com/jobs/',3,true)
on conflict (company) do update set
  sector = excluded.sector,
  careers_url = excluded.careers_url,
  priority = excluded.priority,
  enabled = excluded.enabled,
  updated_at = now();